name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SDL libraries
      run: sudo apt-get install libsdl2-dev libsdl2-ttf-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build frontend
      working-directory: nes_wasm
      run: |
        cargo install wasm-pack
        npm install
        npm run build
        rm ../docs/*
        cp dist/* ../docs
